#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : A Python Implementation of CompEcon  # The title of the book. Will be placed in the left navbar.
author                      : Randall Romero Aguilar  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : figures/r2-logo.png  # A path to the book logo


only_build_toc_files:    true

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : 600
  stderr_output               : remove-warn

sphinx:
  config:
    language : en
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js


parse:
  myst_enable_extensions:
    - deflist
    - amsmath
    #- colon_fence
    - dollarmath
    - substitution

bibtex_bibfiles:
   - references.bib

latex:
  latex_engine              : xelatex



#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/randall-romero/compecon/  # The URL to your book's repository
  path_to_book              : "/"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links


#######################################################################################
# HTML-specific settings
html:
  favicon                   : "figures/r2-logo-icon.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : <a href="http://randall-romero.com">randall-romero.com</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : "289398777"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://randall-romero.github.io/compecon/"  # The base URL where your book will be hosted. Used for creating image previews and social links.
  comments:
    hypothesis              : false
    utterances              : false
